name: master-gesbd

channels:
  - defaults
  - conda-forge

dependencies:
  - python==3.10
  - pymongo
  - python-dotenv
  - dotenv
  - ipykernel
  - transformers
  - sentence-transformers
  - pytorch
  - elasticsearch
  - sentencepiece
  - httpx
  - sparqlwrapper
  - pip==20.2