name: master-gesbd

channels:
  - defaults
  - conda-forge

dependencies:
  - python==3.10
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pymongo
  - python-dotenv
  - dotenv
  - ipykernel
  - transformers
  - datasets
  - pytorch
  - elasticsearch
  - sentencepiece
  - httpx
  - pip==20.2